### ISSUE TITLE
[Formatting]: Adding Scale, Rotation, and Position Modifiers: Multiple images are inline with text

### ISSUE THREAD

**Issue by LB-RobertBaczkowski** [o3de/o3de.org#205]
Link: https://o3deorg.netlify.app/docs/user-guide/gems/reference/vegetation/procedures/adding-modifiers/

Multiple images on the page are placed inline with the text causing them to break page layout (most noticeable when resizing the page's width).

Mentioned images:
![Scale1](https://user-images.githubusercontent.com/80751316/111785763-4c959500-88bd-11eb-832d-ae18d31e62c9.PNG)
![Scale2](https://user-images.githubusercontent.com/80751316/111785765-4d2e2b80-88bd-11eb-9b3c-3537592be5dd.PNG)
![Scale3](https://user-images.githubusercontent.com/80751316/111785766-4d2e2b80-88bd-11eb-89d7-a2b6acbe060a.PNG)
![Scale4](https://user-images.githubusercontent.com/80751316/111785769-4d2e2b80-88bd-11eb-8817-5e86702f3454.PNG)
![Scale5](https://user-images.githubusercontent.com/80751316/111785771-4dc6c200-88bd-11eb-9e38-c98c96f4db1d.PNG)

**Comment by FiniteStateGit** [comment]
Hello @LB-RobertBaczkowski this issue should be resolved with #870 merged.  Thank you for raising the issue.

**Comment by LB-RobertBaczkowski** [comment]
The page has been moved to https://o3de.org/docs/user-guide/gems/reference/environment/vegetation/procedures/adding-modifiers/
While it does not happen in the middle of a sentence, the issue still occurs for Point 7 of the section "Adding a Position Modifier": 
![image](https://user-images.githubusercontent.com/80751316/133046287-a8178146-a28f-43c5-93ca-cb05ed9a36f0.png)

**Comment by FiniteStateGit** [comment]
Fixed in https://github.com/o3de/o3de.org/pull/891.

**Comment by LB-RobertBaczkowski** [comment]
Fix confirmed, although the image is not perfectly in line with other images on the page, as seen below. This should also be adjusted.
![image](https://user-images.githubusercontent.com/80751316/141084970-1924a624-c55b-4723-9fc7-caa7e6b4f3e1.png)
