### ISSUE TITLE
[ISSUE][DOCS] Working with the 3D Viewport contains multiple broken links

### ISSUE THREAD

**Issue by LB-JaroslawGaweda** [o3de/o3de.org#2287]
## Describe the issue
There are issues regarding broken links on the [Working with the 3D Viewport ](https://www.o3de.org/docs/user-guide/editor/viewport/) documentation page:

Working with the 3D Viewport section - [UI widgets](https://www.o3de.org/docs/user-guide/editor/viewport/#ui-widgets)
Reference space widget section- [Transform component](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5ctransform)
Component mode switcher section - [Shape](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5cshape)
[White Box Tool](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5cshape%5cwhite-box)
[Spline](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5cshape%5cspline)
[Non-uniform Scale](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5cnon-uniform-scale)
[PhysX Collider](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5cphysx%5ccollider)
[PhysX Ball Joint](https://www.o3de.org/docs/user-guide/editor/viewport/%5cdocs%5cuser-guide%5ccomponents%5creference%5cphysx%5cball-joint)

Please note that this issue should be considered as a Critical.
## Impacted page(s)

[Working with the 3D Viewport ](https://www.o3de.org/docs/user-guide/editor/viewport/)

## Expected experience

Documentation contains no errors.

**Comment by FiniteStateGit** [comment]
Fixed with #2289.

**Comment by LB-JaroslawGaweda** [comment]
We suggest reopening the issue as it still occurs. Please note that we do not have enough permissions to do it ourselves. The [UI widgets](https://www.o3de.org/docs/user-guide/editor/viewport/#ui-widgets) link in the Working with the 3D Viewport section - does nothing and should be changed to https://www.o3de.org/docs/user-guide/editor/viewport/#viewport-ui-widgets.
